// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import 'dotenv/config';
// import { defineConfig } from 'prisma/config';

// export default defineConfig({
//   schema: 'prisma/schema.prisma',
//   migrations: {
//     path: 'prisma/migrations',
//     seed: 'ts-node prisma/seed.ts', // ← thêm dòng này
//   },
//   datasource: {
//     url: process.env['DATABASE_URL'],
//   },
// });

import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Chỉ CLI đọc file này. App NestJS KHÔNG đọc, mà dùng DATABASE_URL trong PrismaService.
    // Migrate cần kết nối trực tiếp: PgBouncer (pooler) không hỗ trợ advisory lock
    // mà Prisma dùng để tránh 2 lần migrate chạy chồng lên nhau.
    url: env('DIRECT_URL'),
  },
});
